module.exports = {
  useTabs: true,
  tabWidth: 2,
  singleQuote: true,
  trailingComma: "all",
  printWidth: 100,
  semi: false,
  arrowParens: "avoid",
  plugins: ["prettier-plugin-svelte", "@trivago/prettier-plugin-sort-imports"],
  pluginSearchDirs: ["."],
  overrides: [{ files: "*.svelte", options: { parser: "svelte" } }],
  importOrder: ["^@svelte", "^@", "^\\w", "^[$]\\w", "^[./]"],
  importOrderParserPlugins: ["typescript", "decorators-legacy"],
  importOrderSeparation: true,
  importOrderSortSpecifiers: true,
};
